namespace ERPLite.Users.Infrastructure.EntityTypeConfigurations
{
    using ERPLite.Users.Domain.Entities;

    using Microsoft.EntityFrameworkCore;
    using Microsoft.EntityFrameworkCore.Metadata.Builders;

    using System;

    /// <summary>
    /// Defines the entity type configuration for the <see cref="Role"/> entity,
    /// </summary>
    public class RolesEntityTypeConfiguration : IEntityTypeConfiguration<Role>
    {
        /// <summary>
        /// Properties and constraints configuration for the <see cref="Role"/> entity.
        /// </summary>
        /// <param name="builder"></param>
        public void Configure(EntityTypeBuilder<Role> role)
        {
            // Propertiy data types configurations for the Role entity
            _ = role
                .Property(r => r.Id)
                // each role will have a unique identifier generated by the database using the NEWID() function
                .HasDefaultValueSql("NEWID()", "DF_Roles_Id")
                // the Id property is required and cannot be null
                .IsRequired();

            _ = role
                .Property(r => r.Name)
                // the Name property has a maximum length of 200 characters
                .HasMaxLength(200)
                // the Name property is required and cannot be null
                .IsRequired()
                // the Name property is stored as Unicode in the database, allowing for international characters
                .IsUnicode();

            // Propertiy constraints configurations for the Role entity
            _ = role
                // the Id property is the primary key of the Roles table
                .HasKey(r => r.Id)
                // the primary key constraint is named "PK_Roles_Id"
                .HasName("PK_Roles_Id");

            _ = role
                // the Id property has a unique index to ensure that each role has a unique identifier
                .HasIndex(r => r.Id)
                // the unique index on the Id property is named "IX_Roles_Id"
                .HasDatabaseName("IX_Roles_Id")
                // the unique index on the Id property ensures that two roles can not have the same Id value
                .IsUnique();

            _ = role
                // the Name property has a unique index to ensure that each role has a unique name
                .HasIndex(r => r.Name)
                // the unique index on the Name property is named "IX_Roles_Name"
                .HasDatabaseName("IX_Roles_Name")
                // the unique index on the Name property ensures that two roles can not have the same Name value
                .IsUnique();

            // check constraints definitions for the Roles entity
            _ = role.ToTable(x =>
            {
                // the check constraint "CK_Users_Name" ensures that the Name property has a minimum length of 2 characters
                _ = x.HasCheckConstraint("CK_Roles_Name", "LEN(Name) >= 2");
            });

            // Seeding initial data for the Roles entity
            _ = role.HasData(
                new Role
                {
                    Id = new Guid("a01eb327-d8de-43fd-b21b-d44688e827de"),
                    Name = "Admin",
                });
        }
    }
}
