namespace ERPLite.Users.Infrastructure.EntityTypeConfigurations
{
    using ERPLite.Users.Domain.Entities;

    using Microsoft.EntityFrameworkCore;
    using Microsoft.EntityFrameworkCore.Metadata.Builders;

    /// <summary>
    /// Defines the entity type configuration for the <see cref="User"/> entity, 
    /// specifying how it should be mapped to the database schema.
    /// </summary>
    public class UsersEntityTypeConfiguration : IEntityTypeConfiguration<User>
    {
        /// <summary>
        /// This method configures the properties and relationships of the <see cref="User"/> entity,
        /// </summary>
        /// <param name="user"></param>
        public void Configure(EntityTypeBuilder<User> user)
        {
            // Propertiy data types configurations for the User entity
            _ = user
                .Property(u => u.Id)
                // each user will have a unique identifier generated by the database using the NEWID() function
                .HasDefaultValueSql("NEWID()", "DF_Users_Id")
                // the Id property is required and cannot be null
                .IsRequired();

            _ = user
                .Property(u => u.Name)
                // the Name property has a maximum length of 200 characters
                .HasMaxLength(200)
                // the Name property is required and cannot be null
                .IsRequired()
                // the Name property is stored as Unicode in the database, allowing for international characters
                .IsUnicode();

            _ = user
                .Property(u => u.Email)
                // the Email property has a maximum length of 500 characters
                .HasMaxLength(500)
                // the Email property is required and cannot be null
                .IsRequired()
                // the Email property is stored as Unicode in the database, allowing for international characters
                .IsUnicode();

            _ = user
                .Property(u => u.Username)
                // the Username property has a maximum length of 50 characters
                .HasMaxLength(50)
                // the Username property is required and cannot be null
                .IsRequired()
                // the Username property is stored as Unicode in the database, allowing for international characters
                .IsUnicode();

            _ = user
                .Property(u => u.Password)
                // the Password property is stored as SHA512 hash and has a maximum length of 64 characters
                .HasMaxLength(64)
                // the Password property is required and cannot be null
                .IsRequired();

            // Propertiy constraints configurations for the User entity
            _ = user
                // the Id property is the primary key of the Users table
                .HasKey(u => u.Id)
                // the primary key constraint is named "PK_Users_Id"
                .HasName("PK_Users_Id");

            _ = user
                // the Id property has a unique index to ensure that each user has a unique identifier
                .HasIndex(u => u.Id)
                // the unique index on the Id property is named "IX_Users_Id"
                .HasDatabaseName("IX_Users_Id")
                // the unique index on the Id property ensures that two users can not have the same Id value
                .IsUnique();

            _ = user
                // the Email property has a unique index to ensure that each user has a unique email address
                .HasIndex(u => u.Email)
                // the unique index on the Email property is named "IX_Users_Email"
                .HasDatabaseName("IX_Users_Email")
                // the unique index on the Email property ensures that two users can not have the same email address
                .IsUnique();

            _ = user
                // the Username property has a unique index to ensure that each user has a unique username
                .HasIndex(u => u.Username)
                // the unique index on the Username property is named "IX_Users_Username"
                .HasDatabaseName("IX_Users_Username")
                // the unique index on the Username property ensures that two users can not have the same username
                .IsUnique();

            // check constraints definitions for the User entity
            _ = user.ToTable(x =>
            {
                // the check constraint "CK_Users_Name" ensures that the Name property has a minimum length of 2 characters
                _ = x.HasCheckConstraint("CK_Users_Name", "LEN(Name) >= 2");

                // the check constraint "CK_Users_Email" ensures that the Email property has a minimum length of 5 characters
                _ = x.HasCheckConstraint("CK_Users_Email", "LEN(Email) >= 5");

                // the check constraint "CK_Users_Username" ensures that the Username property has a minimum length of 5 characters
                _ = x.HasCheckConstraint("CK_Users_Username", "LEN(Username) >= 5");

                // the check constraint "CK_Users_Password" ensures that the Password property has a length of exactly 64 characters, which is the expected length for a SHA512 hash
                _ = x.HasCheckConstraint("CK_Users_Password", "LEN(Password) = 64");
            });
        }
    }
}
