// <auto-generated />
using System;
using ERPLite.Users.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ERPLite.Users.Infrastructure.Migrations
{
    [DbContext(typeof(UsersDbContext))]
    [Migration("20260318164927_DataSeeding")]
    partial class DataSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ERPLite.Users.Domain.Entities.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("Lang")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id")
                        .HasName("PK_Resources_Id");

                    b.HasIndex(new[] { "Lang", "Name" }, "UQ_Resources_Lang_Name")
                        .IsUnique();

                    b.ToTable("Resources", t =>
                        {
                            t.HasCheckConstraint("CK_Resources_Lang", "LEN(Lang) >= 2");

                            t.HasCheckConstraint("CK_Resources_Name", "LEN(Name) >= 2");
                        });
                });

            modelBuilder.Entity("ERPLite.Users.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()", "DF_Roles_Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id")
                        .HasName("PK_Roles_Id");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("IX_Roles_Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Roles_Name");

                    b.ToTable("Roels", t =>
                        {
                            t.HasCheckConstraint("CK_Roles_Name", "LEN(Name) >= 2");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("a01eb327-d8de-43fd-b21b-d44688e827de"),
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("ERPLite.Users.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()", "DF_Users_Id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_Users_Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Username");

                    b.ToTable("Users", t =>
                        {
                            t.HasCheckConstraint("CK_Users_Email", "LEN(Email) >= 5");

                            t.HasCheckConstraint("CK_Users_Name", "LEN(Name) >= 2");

                            t.HasCheckConstraint("CK_Users_Password", "LEN(Password) = 128");

                            t.HasCheckConstraint("CK_Users_Username", "LEN(Username) >= 5");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("8545b412-69ab-4a15-97d1-193b61d68507"),
                            Email = "noreply@admin.info",
                            Name = "Super User",
                            Password = "FB539A1B5A7880B8AC7D0D37F57F51C3065344A4402B553586CBA7B29E8168EB9BF94A24E6AB9F76364FDE904E4D03561A715F4BFF14A37AC5D1F9F7C1D7C3D4",
                            Username = "admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
